"""Home Generative Agent core module."""

from .conversation_helpers import (
    _convert_schema_json_to_yaml,
    _fix_entity_ids_in_text,
    _is_dashboard_request,
    _maybe_fix_dashboard_entities,
    _resolve_entity_id,
)
from .image_entity import ImageEntity
from .migrations import migrate_person_gallery
from .person_gallery import PersonGalleryDAO
from .recognized_sensor import RecognizedPeopleSensor
from .runtime import HGAData
from .utils import (
    CannotConnectError,
    InvalidAuthError,
    configured_ollama_urls,
    default_mobile_notify_service,
    discover_mobile_notify_service,
    dispatch_on_loop,
    ensure_http_url,
    extract_final,
    gemini_healthy,
    generate_embeddings,
    list_mobile_notify_services,
    list_ollama_models,
    ollama_healthy,
    ollama_url_for_category,
    openai_healthy,
    reasoning_field,
    validate_db_uri,
    validate_face_api_url,
    validate_gemini_key,
    validate_ollama_url,
    validate_openai_key,
)
from .video_analyzer import VideoAnalyzer
from .video_helpers import (
    apply_name_substitution,
    clean_frame_text,
    crop_resize_encode_jpeg,
    dedupe_desc,
    dhash_bytes,
    ensure_dir,
    epoch_from_path,
    format_subject,
    hamming64,
    has_human_terms,
    latest_target,
    limit_sentences_and_chars,
    load_image_rgb,
    mirror_to_www,
    order_batch,
    publish_latest_atomic,
    put_with_backpressure,
)

__all__ = [
    "CannotConnectError",
    "HGAData",
    "ImageEntity",
    "InvalidAuthError",
    "PersonGalleryDAO",
    "RecognizedPeopleSensor",
    "VideoAnalyzer",
    "_convert_schema_json_to_yaml",
    "_fix_entity_ids_in_text",
    "_is_dashboard_request",
    "_maybe_fix_dashboard_entities",
    "_resolve_entity_id",
    "apply_name_substitution",
    "clean_frame_text",
    "configured_ollama_urls",
    "crop_resize_encode_jpeg",
    "dedupe_desc",
    "default_mobile_notify_service",
    "dhash_bytes",
    "discover_mobile_notify_service",
    "dispatch_on_loop",
    "ensure_dir",
    "ensure_http_url",
    "epoch_from_path",
    "extract_final",
    "format_subject",
    "gemini_healthy",
    "generate_embeddings",
    "hamming64",
    "has_human_terms",
    "latest_target",
    "limit_sentences_and_chars",
    "list_mobile_notify_services",
    "list_ollama_models",
    "load_image_rgb",
    "migrate_person_gallery",
    "mirror_to_www",
    "ollama_healthy",
    "ollama_url_for_category",
    "openai_healthy",
    "order_batch",
    "publish_latest_atomic",
    "put_with_backpressure",
    "reasoning_field",
    "validate_db_uri",
    "validate_face_api_url",
    "validate_gemini_key",
    "validate_ollama_url",
    "validate_openai_key",
]
