blueprint:
  name: State of the Home (Home Generative Agent)
  author: goruck
  description: >
    Periodically generate an AI-powered summary of Home Assistant entities exposed to assistant agents.
    Sends notifications (configurable) with the summary.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent/tree/main/blueprints/hga_summary.yaml

  input:
    time_pattern:
      name: Time Pattern
      description: cron-like time pattern (e.g., /30 for every 30 mins)
      selector:
        text:
          multiline: false

    message:
      name: Prompt
      description: Model prompt to create the summary
      default: >
        Provide the latest summary of the house's state and an analysis of the camera images.
        Draw conclusions from this data including presence of people and pets inside the house.
      selector:
        text:
          multiline: true

    agent_id:
      name: Agent ID
      description: The conversation agent to process the prompt.
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      description: A unique identifier for the conversation session.
      default: hga_automation_summary
      selector:
        text:
          multiline: false

    notify_service:
      name: Primary Notify Service
      description: Notify service to send the alert (e.g., notify.notify or notify.my_group).
      default: notify.notify
      selector:
        text:
          multiline: false

    mobile_notify_service:
      name: Mobile Notify Service (Optional, preferred)
      description: >
        e.g., notify.mobile_app_evas_iphone. If set, this is used for mobile push.
        Leave blank to skip or to use the device selector fallback.
      default: ""
      selector:
        text:
          multiline: false

    mobile_device:
      name: Mobile Device (Optional, fallback)
      description: Select a mobile_app device to also receive a push notification.
      default: ""
      selector:
        device:
          integration: mobile_app

    send_persistent:
      name: Also create a persistent notification
      default: true
      selector:
        boolean: {}

triggers:
  - platform: time_pattern
    minutes: !input time_pattern

conditions: []

actions:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_automation_summary_output

  - variables:
      hga_msg: >-
        {{ hga_automation_summary_output.get('response', {})
                                         .get('speech', {})
                                         .get('plain', {})
                                         .get('speech', '') | string }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ hga_msg | length > 0 }}"
        sequence:
          # Optional persistent notification
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ inputs.send_persistent }}"
                sequence:
                  - service: notify.persistent_notification
                    data:
                      title: HGA Automation Summary
                      message: "{{ hga_msg }}"
            default: []

          # Primary notify
          - service: !input notify_service
            data:
              title: HGA Automation Summary
              message: "{{ hga_msg }}"

          # Mobile push — prefer explicit service if provided
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (inputs.mobile_notify_service | default('') | trim) != '' }}"
                sequence:
                  - service: !input mobile_notify_service
                    data:
                      title: HGA Automation Summary
                      message: "{{ hga_msg }}"
              - conditions:
                  - condition: template
                    value_template: "{{ (inputs.mobile_device | default('') | string | length) > 0 }}"
                sequence:
                  - service: notify.notify
                    data:
                      title: HGA Automation Summary
                      message: "{{ hga_msg }}"
                      target:
                        - !input mobile_device
            default: []

mode: single
