blueprint:
  name: Home Generative Agent State of the Home Summary
  author: goruck
  description: >
    Periodically prompts the Home Generative Agent to summarize the current state of your home.
    Pushes a mobile notification and/or persistent notification with the response.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent

  input:
    interval:
      name: Interval
      description: Run every N minutes (fixed options)
      default: "30"
      selector:
        select:
          options:
            - "10"
            - "20"
            - "30"
            - "40"
            - "50"
            - "60"

    message:
      name: Prompt
      description: Prompt to summarize home state.
      default: Summarize the current state of the home, including lights, windows, doors, locks, occupancy, and alarms.
      selector:
        text:
          multiline: false

    agent_id:
      name: Agent ID
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      default: hga_home_summary
      selector:
        text:
          multiline: false

    mobile_push_service:
      name: Mobile Push Notify Service (Optional)
      description: Exact service name (e.g., notify.mobile_app_lindos_iphone). Leave blank to skip mobile push.
      default: ""
      selector:
        text:
          multiline: false

    send_persistent:
      name: Also send a persistent notification?
      default: true
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "*"

condition:
  - condition: template
    value_template: >
      {% set v_interval = ('' ~ !input interval) | int %}
      {% set v_now_minutes = now().hour * 60 + now().minute %}
      {{ v_now_minutes % v_interval == 0 }}

action:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_home_summary_output

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ 'no' not in (hga_home_summary_output['response']['speech']['plain']['speech'] | lower) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input send_persistent }}"
                sequence:
                  - service: persistent_notification.create
                    data:
                      title: State of the Home
                      message: "{{ hga_home_summary_output['response']['speech']['plain']['speech'] }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input mobile_push_service != '' }}"
                sequence:
                  - service: !input mobile_push_service
                    data:
                      title: State of the Home
                      message: "{{ hga_home_summary_output['response']['speech']['plain']['speech'] }}"

mode: single
