blueprint:
  name: Home Generative Agent Scene Analyzer
  author: goruck
  description: >
    Periodically generate camera image scene analysis by prompting the generative agent.
    Sends notifications only if the model detects a requested object in the prompt.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent/tree/main/blueprints/hga_scene_analysis.yaml

  input:
    time_pattern:
      name: Time Pattern
      description: cron-like time pattern (e.g., /30 for every 30 mins)
      selector:
        text:
          multiline: false

    message:
      name: Prompt
      description: Model prompt to generate camera image scene analysis.
      default: Check the front porch camera for one or more boxes.
      selector:
        text:
          multiline: false

    agent_id:
      name: Agent ID
      description: The conversation agent to process the prompt.
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      description: A unique identifier for the conversation session.
      default: hga_scene_analysis
      selector:
        text:
          multiline: false

    notify_service:
      name: Primary Notify Service
      description: Notify service to send the alert (e.g., notify.notify or notify.my_group).
      default: notify.notify
      selector:
        text:
          multiline: false

    mobile_notify_service:
      name: Mobile Notify Service (Optional, preferred)
      description: e.g., notify.mobile_app_evas_iphone. If set, used for mobile push.
      default: ""
      selector:
        text:
          multiline: false

    mobile_device:
      name: Mobile Device (Optional, fallback)
      description: Select a mobile_app device to also receive a push notification.
      default: ""
      selector:
        device:
          integration: mobile_app

    send_persistent:
      name: Also create a persistent notification
      default: true
      selector:
        boolean: {}

triggers:
  - platform: time_pattern
    minutes: !input time_pattern

conditions: []

actions:
  # Run the agent
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_scene_analysis_output

  # Mirror inputs into runtime variables and extract message once
  - variables:
      hga_msg: >-
        {{ hga_scene_analysis_output.get('response', {})
                                    .get('speech', {})
                                    .get('plain', {})
                                    .get('speech', '') | string }}
      _send_persistent: !input send_persistent
      _mobile_notify_service: !input mobile_notify_service
      _mobile_device: !input mobile_device

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'no' not in (hga_msg | lower) }}"
        sequence:
          # Optional persistent notification
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ _send_persistent }}"
                sequence:
                  - service: notify.persistent_notification
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
            default: []

          # Primary notify
          - service: !input notify_service
            data:
              title: HGA Scene Analysis
              message: "{{ hga_msg }}"

          # Mobile push — prefer explicit service if provided; else fallback to device target
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (_mobile_notify_service | trim) != '' }}"
                sequence:
                  - service: "{{ _mobile_notify_service }}"
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
              - conditions:
                  - condition: template
                    value_template: "{{ (_mobile_device | string | length) > 0 }}"
                sequence:
                  - service: notify.notify
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
                      target:
                        - "{{ _mobile_device }}"
            default: []

mode: single
