blueprint:
  name: Home Generative Agent Scene Analyzer
  author: goruck
  description: >
    Periodically prompt the Home Generative Agent to analyze a camera scene.
    Sends a persistent notification and/or mobile push if the agent detects something relevant.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent

  input:
    interval_minutes:
      name: Interval in Minutes
      description: Run automation every N minutes (e.g., 30 for every half hour).
      default: 30
      selector:
        number:
          min: 1
          max: 1440
          mode: box

    message:
      name: Prompt
      description: What the agent should evaluate in the image.
      default: Check the front porch camera for one or more boxes.
      selector:
        text:
          multiline: false

    agent_id:
      name: Agent ID
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      default: hga_scene_analysis
      selector:
        text:
          multiline: false

    mobile_push_service:
      name: Mobile Push Notify Service (Optional)
      description: Exact service name (e.g., notify.mobile_app_yourdevice)
      default: ""
      selector:
        text:
          multiline: false

    send_persistent:
      name: Also send a persistent notification?
      default: true
      selector:
        boolean: {}

variables:
  v_push: !input mobile_push_service
  v_persist: !input send_persistent
  v_interval: !input interval_minutes

trigger:
  - platform: template
    value_template: >
      {% set minutes = now().hour * 60 + now().minute %}
      {{ v_interval > 0 and (minutes % v_interval) == 0 }}

condition: []

action:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_scene_analysis_output

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ 'no' not in (hga_scene_analysis_output['response']['speech']['plain']['speech'] | lower) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_persist }}"
                sequence:
                  - service: persistent_notification.create
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_push != '' }}"
                sequence:
                  - service: "{{ v_push }}"
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"

mode: single
