blueprint:
  name: State of the Home Summary
  author: goruck
  description: >
    Periodically generate an AI-powered summary of Home Assistant entities exposed to assistant agents.
    Sends a persistent notification and/or mobile push with the summary.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent

  input:
    interval:
      name: Interval
      description: Run every N minutes (fixed options)
      default: "30"
      selector:
        select:
          options:
            - "10"
            - "20"
            - "30"
            - "40"
            - "50"
            - "60"

    message:
      name: Prompt
      description: Model prompt to create the summary
      default: >
        Provide the latest summary of the house's state and an analysis of the camera images.
        Draw conclusions from this data including presence of people and pets inside the house.
      selector:
        text:
          multiline: true

    agent_id:
      name: Agent ID
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      default: hga_summary
      selector:
        text:
          multiline: false

    mobile_push_service:
      name: Mobile Push Notify Service (Optional)
      description: Exact service name (e.g., notify.mobile_app_lindos_iphone). Leave blank to skip mobile push.
      default: ""
      selector:
        text:
          multiline: false

    send_persistent:
      name: Also send a persistent notification?
      default: true
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "*"

variables:
  i_interval: !input interval
  v_interval: "{{ i_interval | int }}"
  v_now_minutes: "{{ now().hour * 60 + now().minute }}"
  v_push: !input mobile_push_service
  v_persist: !input send_persistent

condition:
  - condition: template
    value_template: "{{ v_now_minutes | int % v_interval == 0 }}"

action:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_summary_output

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ v_persist }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: HGA Automation Summary
              message: "{{ hga_summary_output['response']['speech']['plain']['speech'] }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ v_push != '' }}"
        sequence:
          - service: "{{ v_push }}"
            data:
              title: HGA Automation Summary
              message: "{{ hga_summary_output['response']['speech']['plain']['speech'] }}"

mode: single
