blueprint:
  name: Home Generative Agent State of the Home Summary
  author: goruck
  description: >
    Periodically ask the Home Generative Agent for a summary of the home's state.
    Sends a persistent notification and/or mobile push if any content is returned.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent

  input:
    interval_minutes:
      name: Interval in Minutes
      description: Run automation every N minutes (e.g., 30 for every half hour).
      default: 30
      selector:
        number:
          min: 1
          max: 1440
          mode: box

    message:
      name: Prompt
      description: Model prompt to create the summary.
      default: >
        Provide the latest summary of the house's state and an analysis of the camera images.
        Draw conclusions from this data including presence of people and animals inside and outside the house.
      selector:
        text:
          multiline: true

    agent_id:
      name: Agent ID
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      default: hga_automation_summary
      selector:
        text:
          multiline: false

    mobile_push_service:
      name: Mobile Push Notify Service (Optional)
      description: Exact service name (e.g., notify.mobile_app_lindos_iphone). Leave blank to skip mobile push.
      default: ""
      selector:
        text:
          multiline: false

    send_persistent:
      name: Also send a persistent notification?
      default: true
      selector:
        boolean: {}

variables:
  v_push: !input mobile_push_service
  v_persist: !input send_persistent

  trigger:
  - platform: template
    value_template: >
      {% set minutes = now().hour * 60 + now().minute %}
      {{ (minutes % (!input interval_minutes)) == 0 }}

condition: []

action:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: !input message
      conversation_id: !input conversation_id
    response_variable: hga_automation_summary_output

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ (hga_automation_summary_output['response']['speech']['plain']['speech'] | string) | length > 0 }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_persist }}"
                sequence:
                  - service: persistent_notification.create
                    data:
                      title: HGA Automation Summary
                      message: "{{ hga_automation_summary_output['response']['speech']['plain']['speech'] }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_push != '' }}"
                sequence:
                  - service: "{{ v_push }}"
                    data:
                      title: HGA Automation Summary
                      message: "{{ hga_automation_summary_output['response']['speech']['plain']['speech'] }}"

mode: single
