blueprint:
  name: Home Generative Agent State of the Home Summary
  author: goruck
  description: >
    Periodically prompt the Home Generative Agent to summarize the full current state of the home.
    Sends a persistent notification and/or mobile push if the summary contains anything notable.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent

  input:
    interval:
      name: Interval
      description: Run every N minutes (fixed options)
      default: "30"
      selector:
        select:
          options:
            - "10"
            - "20"
            - "30"
            - "40"
            - "50"
            - "60"

    agent_id:
      name: Agent ID
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false

    conversation_id:
      name: Conversation ID
      default: hga_state_summary
      selector:
        text:
          multiline: false

    mobile_push_service:
      name: Mobile Push Notify Service (Optional)
      description: Exact service name (e.g., notify.mobile_app_lindos_iphone). Leave blank to skip mobile push.
      default: ""
      selector:
        text:
          multiline: false

    send_persistent:
      name: Also send a persistent notification?
      default: true
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "*"

variables:
  v_push: !input mobile_push_service
  v_persist: !input send_persistent
  v_interval: "{{ i_interval | int }}"
  i_interval: !input interval
  v_now_minutes: "{{ now().hour * 60 + now().minute }}"
  v_prompt: >
    Summarize the current state of the home using all sensor, lock, and camera data. 
    Be concise but mention anything open, unlocked, left on, or unusual.

condition:
  - condition: template
    value_template: "{{ v_now_minutes | int % v_interval == 0 }}"

action:
  - service: conversation.process
    data:
      agent_id: !input agent_id
      text: "{{ v_prompt }}"
      conversation_id: !input conversation_id
    response_variable: hga_state_summary_output

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ 'nothing to report' not in (hga_state_summary_output['response']['speech']['plain']['speech'] | lower) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_persist }}"
                sequence:
                  - service: persistent_notification.create
                    data:
                      title: HGA Home Summary
                      message: "{{ hga_state_summary_output['response']['speech']['plain']['speech'] }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_push != '' }}"
                sequence:
                  - service: "{{ v_push }}"
                    data:
                      title: HGA Home Summary
                      message: "{{ hga_state_summary_output['response']['speech']['plain']['speech'] }}"

mode: single
