blueprint:
  name: Home Generative Agent Scene Analyzer
  author: goruck
  description: >
    Periodically generate camera image scene analysis by prompting the generative agent.
    Sends notifications only if the model detects a requested object in the prompt.
  domain: automation
  source_url: https://github.com/goruck/home-generative-agent/tree/main/blueprints/hga_scene_analysis.yaml

  input:
    time_pattern:
      name: Time Pattern
      description: cron-like time pattern (e.g., /30 for every 30 mins)
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      description: Model prompt to generate camera image scene analysis.
      default: Check the front porch camera for one or more boxes.
      selector:
        text:
          multiline: false
    agent_id:
      name: Agent ID
      description: The conversation agent to process the prompt.
      default: conversation.home_generative_agent
      selector:
        text:
          multiline: false
    conversation_id:
      name: Conversation ID
      description: A unique identifier for the conversation session.
      default: hga_scene_analysis
      selector:
        text:
          multiline: false
    notify_service:
      name: Primary Notify Service
      description: >
        Notify service to send the alert (e.g., notify.notify or notify.my_group).
      default: notify.notify
      selector:
        text:
          multiline: false
    mobile_device:
      name: Mobile Device (Optional)
      description: Select a mobile_app device to also receive a push notification. Leave empty to disable.
      default: ""
      selector:
        device:
          integration: mobile_app
    send_persistent:
      name: Also create a persistent notification
      default: true
      selector:
        boolean: {}

variables:
  v_msg: !input message
  v_agent: !input agent_id
  v_conv: !input conversation_id
  v_notify: !input notify_service
  v_mobile: !input mobile_device
  v_persist: !input send_persistent

triggers:
  - platform: time_pattern
    minutes: !input time_pattern

conditions: []
  
actions:
  - service: conversation.process
    data:
      agent_id: "{{ v_agent }}"
      text: "{{ v_msg }}"
      conversation_id: "{{ v_conv }}"
    response_variable: hga_scene_analysis_output

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ 'no' not in (hga_scene_analysis_output['response']['speech']['plain']['speech'] | lower) }}
        sequence:
          # Optional persistent notification
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_persist }}"
                sequence:
                  - service: notify.persistent_notification
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"
            default: []

          # Primary OR targeted mobile (avoid duplicates)
          - choose:
              # If mobile device selected AND primary is notify.notify -> send ONLY targeted mobile
              - conditions:
                  - condition: template
                    value_template: "{{ v_mobile != '' and (v_notify | lower) == 'notify.notify' }}"
                sequence:
                  - service: notify.notify
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"
                      target:
                        - "{{ v_mobile }}"
            default:
              # Otherwise send the primary service
              - service: "{{ v_notify }}"
                data:
                  title: HGA Scene Analysis
                  message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"

          # Extra targeted mobile ONLY when primary is neither notify.notify nor a mobile_app service
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ v_mobile != '' and (v_notify | lower) != 'notify.notify' and ((v_notify | lower)[:19] != 'notify.mobile_app_') }}
                sequence:
                  - service: notify.notify
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_scene_analysis_output['response']['speech']['plain']['speech'] }}"
                      target:
                        - "{{ v_mobile }}"
            default: []

mode: single
    response_variable: hga_scene_analysis_output

  # Mirror inputs into runtime variables and extract message once
  - variables:
      hga_msg: >-
        {{ hga_scene_analysis_output.get('response', {})
                                    .get('speech', {})
                                    .get('plain', {})
                                    .get('speech', '') | string }}
      _send_persistent: !input send_persistent
      _mobile_notify_service: !input mobile_notify_service
      _mobile_device: !input mobile_device

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'no' not in (hga_msg | lower) }}"
        sequence:
          # Optional persistent notification
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ _send_persistent }}"
                sequence:
                  - service: notify.persistent_notification
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
            default: []

          # Primary notify
          - service: !input notify_service
            data:
              title: HGA Scene Analysis
              message: "{{ hga_msg }}"

          # Mobile push — prefer explicit service if provided; else fallback to device target
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (_mobile_notify_service | trim) != '' }}"
                sequence:
                  - service: "{{ _mobile_notify_service }}"
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
              - conditions:
                  - condition: template
                    value_template: "{{ (_mobile_device | string | length) > 0 }}"
                sequence:
                  - service: notify.notify
                    data:
                      title: HGA Scene Analysis
                      message: "{{ hga_msg }}"
                      target:
                        - "{{ _mobile_device }}"
            default: []

mode: single
